### ISSUE TITLE
d

### ISSUE THREAD

**Issue by topitbopit** [nerve-sys/discordwebhooktoolkit#1]
### hi
this is useless and sucks please fix it now

i made task list for this project sir:
- [ ] fix it
- [x] not fixed
- [x] this sitll has to be fixed
- [ ] make it better and useful 
- [x] currnetly not useful

thank you sir for your time sir

**Comment by nerve-sys** [comment]
🤯

**Comment by nerve-sys** [comment]
ok i fixed it now it is perfect and without flaw

**Comment by topitbopit** [comment]
thank you sir for fixing my issue request sir 
i will let you know sir if i have a new issue request ok sir?

thanks many for your time sir
